#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep bspswallow || bspswallow &
pgrep cleanfullscreen || cleanfullscreen &

~/.config/polybar/launch
~/.config/picom/launch

redshift -P -O 2400 &

#feh --bg-fill ~/Pictures/hibi.png
#feh --bg-fill ~/Pictures/tardis.png
feh --bg-fill ~/Pictures/yuugure.png

xsetroot -cursor_name left_ptr &
fcitx &
greenclip daemon &
dunst &

MONITOR=$(hwinfo --short | grep -i "samsung")
if [[ "$MONITOR" =~ "SAMSUNG" ]]; then
xrandr --output eDP --off
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60
else
xrandr --output eDP --mode 1920x1080 --rate 60
fi

bspc monitor -r eDP
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
bspc config remove_unplugged_monitors = true
bspc config remove_disabled_monitors = true

bspc config split_ratio          0.50
bspc config gapless_monocle      true
bspc config borderless_monocle   true
bspc config top_padding 	 25
bspc config border_width	 3
bspc config window_gap 		 3

bspc normal_border_color 	#21252b
bspc focused_border_color	#434957

bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
