#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch
~/.config/picom/launch

redshift -P -O 2300 &
feh --bg-fill ~/Pictures/yuugure.png

xsetroot -cursor_name left_ptr &
exec --no-startup-id fcitx &
greenclip daemon &

xrandr --output eDP --off
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60

bspc monitor -r eDP
bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
bspc config remove_unplugged_monitors = true
bspc config remove_disabled_monitors = true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 	 23
bspc config border_width	 2
bspc config window_gap 		 5	

bspc normal_border_color 	#0f0f10
bspc focused_border_color	#e0c8aa

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
