# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.config/zsh/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load colors
autoload -U colors && colors

# Change Prompt
PS1="%F{166}[%n%f%F{172}@%f%F{178}%m]%f %F{184}%~%f %F{190}$%f "

# History
HISTSIZE=10000000
SAVEHIST=10000000
HISTFILE=~/.cache/zsh/history

# Tab complete
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)	

# vi keys
bindkey -v
export KEYTIMEOUT=1

# Use vim keys in tab complete menu:
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
bindkey -M menuselect 'j' vi-down-line-or-history

# Make bat the manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export PATH="/home/raynei/.local/bin:$PATH"
export PATH="/home/raynei/.cargo/bin:$PATH"

alias la="exa"
export EDITOR='vim'
alias clearclip="pkill greenclip && greenclip clear && greenclip daemon &"

eval "$(zoxide init zsh)"
fpath=(/home/raynei/.config/zsh/zsh-completions/src $fpath)
source /home/raynei/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source /home/raynei/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.config/zsh/.p10k.zsh.
[[ ! -f ~/.config/zsh/.p10k.zsh ]] || source ~/.config/zsh/.p10k.zsh
